### ISSUE TITLE
Migrate MPS-Gradle-Plugin to Gradle 7.3

### ISSUE THREAD

**Issue by dbinkele** [mbeddr/mps-gradle-plugin#116]

**Comment by sergej-koscejev** [comment]
What’s the motivation for this version specifically? Gradle releases a new version every month or so, they are usually backwards compatible.

**Comment by dbinkele** [comment]
Customer wants the plugin to run on version 7, which is not backward compatible (@coolya)

**Comment by alexanderpann** [comment]
I am closing this issue as we are now using Gradle 7.4.1.
