### ISSUE TITLE
DownloadJbr does not recognize M1 mac

### ISSUE THREAD

**Issue by joswarmer** [mbeddr/mps-gradle-plugin#123]
It seems that the download jbr only looks at the OS "family"  and always returns an X64.  See in DownloadJbrProjectPlugin:

```
     Os.isFamily(Os.FAMILY_MAC) -> {
             "com.jetbrains.jdk:jbr:$version:osx-x64@tgz"
     }
```

It should look at the processor (Intel or M1) and return the M1 jbr in case of an M1 processor.

**Comment by sergej-koscejev** [comment]
#118 should address this once merged.

**Comment by joswarmer** [comment]
Ok,PR 118 is it indeed.
