### ISSUE TITLE
Support IPv6 access

### ISSUE THREAD

**Issue by AtanasM98** [mbeddr/mps-gradle-plugin#124]
We use a runner that uses only IPv6 and the gradle script can't access the needed repositories.

**Comment by AtanasM98** [comment]
[projects.itemis.de](http://projects.itemis.de/) seems not to have an AAAA DNS record.

**Comment by coolya** [comment]
Feel free to consume the artifacts from Github [Packages](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-gradle-registry):  https://github.com/orgs/mbeddr/packages?repo_name=mps-gradle-plugin which has ipV6 support. We have no means to add ipv6 support to projects.itemis.de sorry for that.
