### ISSUE TITLE
Add model checking task

### ISSUE THREAD

**Issue by coolya** [mbeddr/mps-gradle-plugin#21]
A requirement that often pops up from users is the ability to run the model checker from the commandline. 

For instance to fail the build and further generation of a project if it contains any model checking errors.

**Comment by rafaroca** [comment]
I want to do exactly that, fail the build when there are model checker errors. I'd highly appreciate this feature

**Comment by rafaroca** [comment]
@coolya are you actively working on this?

**Comment by coolya** [comment]
@rafaroca yes we are. Currently reviewing some infrastructure changes in #20 that we will need in this task as well. #20 should be merged by the end of this week. Then adding this feature should be straight forward.

**Comment by rafaroca** [comment]
@coolya I see that #20 is now merged. Are you planning to work on the model checker task?

**Comment by rafaroca** [comment]
@coolya any progress on this issue? are you working on this, is there another task blocking? thanks

**Comment by coolya** [comment]
@rafaroca we have a working version of it wich is not yet open source. I expect it to be published in the next two week from now.
